const tracks = [
  {
    name: "Hay Là Chúng Ta Cứ Như Vậy Một Vạn Năm",
    artist: "Hoàng Tiêu Vân | Trường Nguyệt Tẫn Minh OST",
    artwork: "https://i.postimg.cc/sfB4vtbq/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/cunhuvaymotvannam/2.mp3",
  },
  {
    name: "Vở Kịch Của Em x Vây Giữ REMIX",
    artist: "Hồ Phong An x HuyN FT",
    artwork: "https://i.postimg.cc/SQCRjdNk/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/vokichcuaem/2.mp3",
  },
  {
    name: "Yêu Em Nhưng Không Với Tới x Vây Giữ REMIX",
    artist: "DC Tâm x SS x AM Remix",
    artwork: "https://i.postimg.cc/8PTpcV0m/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/yeuemnhungkhongvoitoi/2.mp3",
  },
  {
    name: "Anh Đau Từ Lúc Em Đi",
    artist: "Trần Mạnh Cường",
    artwork: "https://i.postimg.cc/5t3nSLmr/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/anhdautulucemdi/2.mp3",
  },
    {
    name: "Mạnh Bà lofi",
    artist: "Linh Hương Luz",
    artwork: "https://i.postimg.cc/B62DC0sn/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/manhba/2.mp3",
  },
  {
    name: "Địa Đàng REMIX",
    artist: "Hoàng Oanh x ACV",
    artwork: "https://i.postimg.cc/GhwgrL9q/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/diadang/2.mp3",
  },
  {
    name: "Tái Sinh REMIX",
    artist: "Tùng Dương x ACV",
    artwork: "https://i.postimg.cc/mk0vWCJw/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/taisinh/2.mp3",
  },
  {
    name: "Ải Hồng Nhan REMIX",
    artist: "Cần Vinh x Lee Ken",
    artwork: "https://i.postimg.cc/7hLc2m8X/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/aihongnhan/2.mp3",
  },
 {
    name: "Thương Thì Thôi REMIX",
    artist: "Jank",
    artwork: "https://i.postimg.cc/v8Wk4gJp/1.jpg",
    path: ".https://github.com/d4m-dev/media/raw/refs/heads/main/thuongthithoi/2.mp3",
  },
  {
    name: "Ba Kiếp Tình Một Kiếp Duyên lofi",
    artist: "Lâm Tuấn x MewMew lofi",
    artwork: "https://i.postimg.cc/K85HJ6GQ/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/bakieptinhmotkiepduyen/2.mp3",
  },
  {
    name: "Trả Lại Thanh Xuân Cho Em REMIX",
    artist: "Mochiii x Domino Remix",
    artwork: "https://i.postimg.cc/4d3yYRd0/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/tralaithanhxuanchoem/2.mp3",
  },
  {
    name: "Đào Hoa Nặc",
    artist: "旺仔小乔",
    artwork: "https://i.postimg.cc/htC0JcPF/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/daohoanac/2.mp3",
  },
  {
    name: "Em Đồng Ý I Do",
    artist: "ĐỨC PHÚC x 911 x KHẮC HƯNG  OFFICIAL",
    artwork: "https://i.postimg.cc/TYDMgYZM/1.jpg",
    path: "https://github.com/d4m-dev/media/raw/refs/heads/main/weddingsongs/ido.mp3",
  },
  {
    name: "",
    artist: "",
    artwork: "./media//1.jpg",
    path: "./media//2.mp3",
  },
    {
    name: "",
    artist: "",
    artwork: "./media//1.jpg",
    path: "./media//2.mp3",
  },
    {
    name: "",
    artist: "",
    artwork: "./media//1.jpg",
    path: "./media//2.mp3",
  },
];
